name: OumProfile
version: 1.0-HOTFIX

main: dev.oum.profile.OumProfile
api-version: '1.21'
folia-supported: true
author: sun-dev
description: Let players create and switch between different profiles.

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    CoinsEngine:
      load: BEFORE
      required: false
      join-classpath: true
    PlayerPoints:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    MiniPlaceholders:
      load: BEFORE
      required: false
      join-classpath: true